//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoursStudiedSubject
    {
        public int ClassID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public int SubjectID { get; set; }
        public byte SubjectTypeID { get; set; }
        public int HoursStudied { get; set; }
    }
}
