//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolYear
    {
        public SchoolYear()
        {
            this.SchoolClasses = new HashSet<SchoolClass>();
            this.StudentsSchoolYears = new HashSet<StudentsSchoolYear>();
        }
    
        public int SchoolYearID { get; set; }
        public string SchoolYearName { get; set; }
    
        public virtual ICollection<SchoolClass> SchoolClasses { get; set; }
        public virtual ICollection<StudentsSchoolYear> StudentsSchoolYears { get; set; }
    }
}
