//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settlement
    {
        public Settlement()
        {
            this.Settlements1 = new HashSet<Settlement>();
            this.Settlements11 = new HashSet<Settlement>();
            this.Students = new HashSet<Student>();
        }
    
        public int SettlementID { get; set; }
        public string SettlemnetName { get; set; }
        public int ManicipalityID { get; set; }
        public int AreaID { get; set; }
    
        public virtual ICollection<Settlement> Settlements1 { get; set; }
        public virtual Settlement Settlement1 { get; set; }
        public virtual ICollection<Settlement> Settlements11 { get; set; }
        public virtual Settlement Settlement2 { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
