//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.Absences = new HashSet<Absence>();
            this.Marks = new HashSet<Mark>();
        }
    
        public byte TermID { get; set; }
        public string TermName { get; set; }
    
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
    }
}
