//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCardEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectType
    {
        public SubjectType()
        {
            this.Diploms = new HashSet<Diplom>();
            this.HoursStudedSubjects = new HashSet<HoursStudedSubject>();
        }
    
        public byte SubjectTypeID { get; set; }
        public string SubjectType1 { get; set; }
    
        public virtual ICollection<Diplom> Diploms { get; set; }
        public virtual ICollection<HoursStudedSubject> HoursStudedSubjects { get; set; }
    }
}
