//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplom
    {
        public long SudentID { get; set; }
        public int SubjectID { get; set; }
        public byte SujectTypeID { get; set; }
        public Nullable<float> Mark { get; set; }
        public Nullable<int> HoursStudied { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual SubjectType SubjectType { get; set; }
    }
}
