//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalSchoolCardEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalSchoolCardEntities2 : DbContext
    {
        public PersonalSchoolCardEntities2()
            : base("name=PersonalSchoolCardEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Diplom> Diploms { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<HoursStudedSubject> HoursStudedSubjects { get; set; }
        public virtual DbSet<Manicipality> Manicipalities { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Principal> Principals { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolYear> SchoolYears { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsSchoolYear> StudentsSchoolYears { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectType> SubjectTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<TypeAbsence> TypeAbsences { get; set; }
        public virtual DbSet<Absence> Absences { get; set; }
    }
}
