//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public byte TypeAbsencesID { get; set; }
        public long StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public byte TermID { get; set; }
        public string AbsencesNumber { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Student Student { get; set; }
        public virtual Term Term { get; set; }
        public virtual TypeAbsence TypeAbsence { get; set; }
    }
}
