//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Settlements = new HashSet<Settlement>();
        }
    
        public int AreaID { get; set; }
        public string AreaName { get; set; }
    
        public virtual ICollection<Settlement> Settlements { get; set; }
    }
}
