//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Absences = new HashSet<Absence>();
            this.HoursStudedSubjects = new HashSet<HoursStudedSubject>();
            this.Marks = new HashSet<Mark>();
        }
    
        public byte GradeID { get; set; }
        public Nullable<byte> Grade1 { get; set; }
    
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual ICollection<HoursStudedSubject> HoursStudedSubjects { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
    }
}
