//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public long StudentID { get; set; }
        public int SubjectID { get; set; }
        public byte SubjectTypeID { get; set; }
        public byte TermID { get; set; }
        public byte GradeID { get; set; }
        public byte Mark1 { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Term Term { get; set; }
    }
}
