//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCardDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAbsence
    {
        public TypeAbsence()
        {
            this.Absences = new HashSet<Absence>();
        }
    
        public byte TypeAbsenceID { get; set; }
        public string TypeAbsence1 { get; set; }
    
        public virtual ICollection<Absence> Absences { get; set; }
    }
}
